# Copyright (C) Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.
---

version: '3'

output: 'prefixed'

vars:
  GO_PACKAGES:
    sh: 'go list ./...'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'clean'
      - task: 'dependencies'
      - task: 'lint'
      - task: 'test'
      - task: 'build'
    desc: 'Run all continuous-integration-related tasks'

  clean:
    cmds:
      - 'rm -fr nt bin'
      - 'go clean -testcache'
    desc: 'Delete all buildable files and caches'

  build:
    cmds:
      - 'go build ./cmd/nt'
    desc: 'Build the "nt" application'

  dependencies:
    cmds:
      - 'mkdir -p {{.USER_WORKING_DIR}}/bin'
      - 'go install golang.org/x/lint/golint@latest'
      - 'go install honnef.co/go/tools/cmd/staticcheck@v0.6.1'
    env:
      GOBIN: '{{.USER_WORKING_DIR}}/bin'
    desc: 'Install Go dependencies'

  lint:
    cmds:
      - task: 'lint:golint'
      - task: 'lint:staticcheck'
      - task: 'lint:vet'
    desc: 'Run all linting tasks'

  lint:golint:
    cmds:
      - 'bin/golint -set_exit_status {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Golint'

  lint:staticcheck:
    cmds:
      - 'bin/staticcheck {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Staticcheck'

  lint:vet:
    cmds:
      - 'go vet {{catLines .GO_PACKAGES}}'
    desc: 'Lint Go files with Vet'

  test:
    cmds:
      - 'go test -race -shuffle=on {{catLines .GO_PACKAGES}}'
    desc: 'Run all tests'
