# Copyright (C) Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

---
name: 'Lint, Test, and Build Project'

on:
  push:
    branches:
      - 'main'

jobs:
  lint-test-and-build:
    name: 'Lint, test, and build project'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v4'

      - name: 'Set up Go environment'
        uses: 'actions/setup-go@v4'
        with:
          go-version-file: 'go.mod'

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'

      - name: 'Install Golint and Staticcheck'
        run: |
          go install golang.org/x/lint/golint@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: 'Ensure all linting, testing, and building tasks run successfully'
        run: './bin/task ci'
